/-
Copyright (c) 2026 FloatLib
Released under MIT license as described in the file LICENSE.
Authors: FloatLib Team
-/

module

public import Batteries.Data.ByteArray
public import FloatLib.Floats.ExecFloat.Backends.TinyTable.Generic.Indexing
public import FloatLib.Floats.Formats.BinaryInterchange.Model.Carrier

/-!
# Verified byte tables for tiny binary formats

An operation on a format with at most eight stored bits can be compiled into a dense `ByteArray`.
Generation uses the shared `Tabulation` constructors in `Generic.Construction`. Unlike a bijective
`Encoding`, this interface accepts any radix; the lookup theorems therefore carry explicit input
and result bounds.

Public low-bit kernels keep generated arrays in Lean runtime `Thunk` cells. Module initialization
creates the cells without generating a table; the first lookup computes and memoizes the bytes.
The defining `Thunk.get` equation keeps this startup optimization inside the proved boundary. See
Lean 4.33 `Init.Core.Thunk`:
<https://github.com/leanprover/lean4/blob/v4.33.0/src/Init/Core.lean#L109-L153>.
-/

@[expose] public section

namespace FloatLib.Floats.Formats.BinaryInterchange.Model
namespace TinyTable

open FloatLib.Floats.ExecFloat.Backend.TinyTable

/--
Build the row-major byte table of a total binary operation.

Public arithmetic operations are total, so the table stores exactly one encoded result per input
pair. Generating it directly avoids a sentinel encoding for an unused partial-operation case.
-/
def binaryTotal (fmt : FloatFormat) (radix : Nat)
    (op : Model fmt → Model fmt → Model fmt) : ByteArray :=
  Tabulation.binary radix fun x y =>
    UInt8.ofNat (Model.toNatBits (op (Model.ofNatBits x.val) (Model.ofNatBits y.val)))

/-- Build the dense byte table of a total unary operation. -/
def unaryTotal (fmt : FloatFormat) (radix : Nat)
    (op : Model fmt → Model fmt) : ByteArray :=
  ByteArray.ofFn fun x : Fin radix =>
    UInt8.ofNat (Model.toNatBits (op (Model.ofNatBits x.val)))

/-- Build the row-major byte table of a total ternary operation. -/
def ternaryTotal (fmt : FloatFormat) (radix : Nat)
    (op : Model fmt → Model fmt → Model fmt → Model fmt) : ByteArray :=
  Tabulation.ternary radix fun x y z =>
    UInt8.ofNat (Model.toNatBits
      (op (Model.ofNatBits x.val) (Model.ofNatBits y.val) (Model.ofNatBits z.val)))

/--
Delay a total binary table until its first lookup, then retain the generated bytes.

Lean's runtime implements `Thunk` as a thread-safe call-by-need cell. The logical equation below
is definitional, so laziness changes initialization cost without changing the proof boundary.
See `Init.Core.Thunk` in Lean 4.33.0:
<https://github.com/leanprover/lean4/blob/v4.33.0/src/Init/Core.lean#L109-L153>.
-/
def lazyBinaryTotal (fmt : FloatFormat) (radix : Nat)
    (op : Model fmt → Model fmt → Model fmt) : Thunk ByteArray :=
  Thunk.mk fun _ => binaryTotal fmt radix op

/-- Forcing a delayed binary table returns exactly its logical generator. -/
@[simp] theorem lazyBinaryTotal_get (fmt : FloatFormat) (radix : Nat)
    (op : Model fmt → Model fmt → Model fmt) :
    (lazyBinaryTotal fmt radix op).get = binaryTotal fmt radix op := by
  rfl

/-- Delay and memoize a total unary byte table. -/
def lazyUnaryTotal (fmt : FloatFormat) (radix : Nat)
    (op : Model fmt → Model fmt) : Thunk ByteArray :=
  Thunk.mk fun _ => unaryTotal fmt radix op

/-- Forcing a delayed unary table returns exactly its logical generator. -/
@[simp] theorem lazyUnaryTotal_get (fmt : FloatFormat) (radix : Nat)
    (op : Model fmt → Model fmt) :
    (lazyUnaryTotal fmt radix op).get = unaryTotal fmt radix op := by
  rfl

/-- Delay and memoize a total ternary byte table. -/
def lazyTernaryTotal (fmt : FloatFormat) (radix : Nat)
    (op : Model fmt → Model fmt → Model fmt → Model fmt) : Thunk ByteArray :=
  Thunk.mk fun _ => ternaryTotal fmt radix op

/-- Forcing a delayed ternary table returns exactly its logical generator. -/
@[simp] theorem lazyTernaryTotal_get (fmt : FloatFormat) (radix : Nat)
    (op : Model fmt → Model fmt → Model fmt → Model fmt) :
    (lazyTernaryTotal fmt radix op).get = ternaryTotal fmt radix op := by
  rfl

/--
Native binary-table lookup returns the same code generated by the logical operation.

This is the refinement bridge used by direct `UInt8` carriers. The index arithmetic is native at
runtime; all range and no-overflow arguments are proof-only.
-/
theorem lookupBinaryTotalByte
    (fmt : FloatFormat) (radix : Nat) (radixWord : USize)
    (hradixWord : radixWord.toNat = radix)
    (_hradix : 0 < radix)
    (op : Model fmt → Model fmt → Model fmt)
    (left right : UInt8)
    (_hleft : left.toNat < radix)
    (hright : right.toNat < radix)
    (hword :
      left.toNat * radixWord.toNat + right.toNat <
        2 ^ System.Platform.numBits)
    (hindex :
      (binaryByteIndex radixWord left right).toNat <
        (binaryTotal fmt radix op).size) :
    (binaryTotal fmt radix op).uget
        (binaryByteIndex radixWord left right) hindex =
      UInt8.ofNat
        (op
          (Model.ofNatBits (fmt := fmt) left.toNat)
          (Model.ofNatBits (fmt := fmt) right.toNat)).toNatBits := by
  have hidx :
      (binaryByteIndex radixWord left right).toNat =
        left.toNat * radix + right.toNat := by
    simpa only [hradixWord] using binaryByteIndex_toNat radixWord left right hword
  rw [uget_eq_get]
  simpa only [binaryTotal, hidx] using
    Tabulation.getElem_binary radix
      (fun x y => UInt8.ofNat
        (op (Model.ofNatBits (fmt := fmt) x.val) (Model.ofNatBits y.val)).toNatBits)
      ⟨left.toNat, _hleft⟩ ⟨right.toNat, hright⟩
      (by simpa only [binaryTotal, hidx] using hindex)

/--
Native unary-table lookup returns the same code generated by the logical operation.

The byte-to-`USize` conversion is unboxed and the bound argument is erased.
-/
theorem lookupUnaryTotalByte
    (fmt : FloatFormat) (radix : Nat)
    (op : Model fmt → Model fmt)
    (value : UInt8)
    (_hvalue : value.toNat < radix)
    (hindex :
      (unaryByteIndex value).toNat <
        (unaryTotal fmt radix op).size) :
    (unaryTotal fmt radix op).uget (unaryByteIndex value) hindex =
      UInt8.ofNat
        (op (Model.ofNatBits (fmt := fmt) value.toNat)).toNatBits := by
  rw [uget_eq_get]
  unfold unaryTotal at hindex ⊢
  rw [ByteArray.getElem_ofFn]
  simp only [unaryByteIndex_toNat]

/--
Native ternary-table lookup returns the code generated by the logical operation.

The quotient and remainder equations reconstruct the three input coordinates from the native
row-major index. All arithmetic side conditions are proof-only.
-/
theorem lookupTernaryTotalByte
    (fmt : FloatFormat) (radix : Nat) (radixWord : USize)
    (hradixWord : radixWord.toNat = radix)
    (_hradix : 0 < radix)
    (op : Model fmt → Model fmt → Model fmt → Model fmt)
    (left right addend : UInt8)
    (_hleft : left.toNat < radix)
    (hright : right.toNat < radix)
    (haddend : addend.toNat < radix)
    (hleftMul :
      left.toNat * radixWord.toNat <
        2 ^ System.Platform.numBits)
    (hpair :
      left.toNat * radixWord.toNat + right.toNat <
        2 ^ System.Platform.numBits)
    (hpairMul :
      (left.toNat * radixWord.toNat + right.toNat) * radixWord.toNat <
        2 ^ System.Platform.numBits)
    (hword :
      (left.toNat * radixWord.toNat + right.toNat) * radixWord.toNat +
          addend.toNat <
        2 ^ System.Platform.numBits)
    (hindex :
      (ternaryByteIndex radixWord left right addend).toNat <
        (ternaryTotal fmt radix op).size) :
    (ternaryTotal fmt radix op).uget
        (ternaryByteIndex radixWord left right addend) hindex =
      UInt8.ofNat
        (op
          (Model.ofNatBits (fmt := fmt) left.toNat)
          (Model.ofNatBits (fmt := fmt) right.toNat)
          (Model.ofNatBits (fmt := fmt) addend.toNat)).toNatBits := by
  have hidx :
      (ternaryByteIndex radixWord left right addend).toNat =
        (left.toNat * radix + right.toNat) * radix + addend.toNat := by
    simpa only [hradixWord] using
      ternaryByteIndex_toNat radixWord left right addend hleftMul hpair hpairMul hword
  rw [uget_eq_get]
  simpa only [ternaryTotal, hidx] using
    Tabulation.getElem_ternary radix
      (fun x y z => UInt8.ofNat
        (op (Model.ofNatBits (fmt := fmt) x.val)
          (Model.ofNatBits y.val) (Model.ofNatBits z.val)).toNatBits)
      ⟨left.toNat, _hleft⟩ ⟨right.toNat, hright⟩ ⟨addend.toNat, haddend⟩
      (by simpa only [ternaryTotal, hidx] using hindex)

/-- Two in-range words select an in-range row-major entry of a total-operation table. -/
theorem binaryTotal_index_lt
    (fmt : FloatFormat) (radix : Nat)
    (op : Model fmt → Model fmt → Model fmt)
    (x y : Model fmt)
    (hx : Model.toNatBits x < radix)
    (hy : Model.toNatBits y < radix) :
    Model.toNatBits x * radix + Model.toNatBits y <
      (binaryTotal fmt radix op).size := by
  simpa only [binaryTotal, ByteArray.size_ofFn, Nat.mul_comm] using
    Nat.mul_add_lt_mul_of_lt_of_lt hx hy

/-- Three in-range words select an in-range row-major entry of a ternary table. -/
theorem ternaryTotal_index_lt
    (fmt : FloatFormat) (radix : Nat)
    (op : Model fmt → Model fmt → Model fmt → Model fmt)
    (x y z : Model fmt)
    (hx : x.toNatBits < radix)
    (hy : y.toNatBits < radix)
    (hz : z.toNatBits < radix) :
    (x.toNatBits * radix + y.toNatBits) * radix + z.toNatBits <
      (ternaryTotal fmt radix op).size := by
  simpa only [ternaryTotal, ByteArray.size_ofFn, Nat.mul_comm] using
    Nat.mul_add_lt_mul_of_lt_of_lt (Nat.mul_add_lt_mul_of_lt_of_lt hx hy) hz

/--
Reading a total-operation table returns the logical operation result.

The result bound is explicit because the table stores one byte. The input bound reconstructs the
two operands from their row-major index.
-/
theorem lookupTotal
    (fmt : FloatFormat) (radix : Nat) (hradix : 0 < radix)
    (op : Model fmt → Model fmt → Model fmt)
    (x y : Model fmt)
    (hy : Model.toNatBits y < radix)
    (hz : Model.toNatBits (op x y) < 256)
    (hindex :
      Model.toNatBits x * radix + Model.toNatBits y <
        (binaryTotal fmt radix op).size) :
    Model.ofNatBits (fmt := fmt)
        ((binaryTotal fmt radix op)[
          Model.toNatBits x * radix + Model.toNatBits y]'hindex).toNat =
      op x y := by
  have hx : x.toNatBits < radix := by
    have hsize : x.toNatBits * radix + y.toNatBits < radix * radix := by
      simpa only [binaryTotal, ByteArray.size_ofFn] using hindex
    exact (Nat.mul_lt_mul_right hradix).mp
      (Nat.lt_of_le_of_lt (Nat.le_add_right _ _) hsize)
  have hentry := Tabulation.getElem_binary radix
    (fun a b => UInt8.ofNat
      (op (Model.ofNatBits (fmt := fmt) a.val) (Model.ofNatBits b.val)).toNatBits)
    ⟨x.toNatBits, hx⟩ ⟨y.toNatBits, hy⟩ hindex
  unfold binaryTotal
  rw [hentry]
  simp only [ofNatBits_toNatBits, UInt8.toNat_ofNat', Nat.mod_eq_of_lt hz]

/-- Reading a total unary-operation table returns the logical operation result. -/
theorem lookupUnaryTotal
    (fmt : FloatFormat) (radix : Nat)
    (op : Model fmt → Model fmt)
    (x : Model fmt)
    (hz : Model.toNatBits (op x) < 256)
    (hindex : Model.toNatBits x < (unaryTotal fmt radix op).size) :
    Model.ofNatBits (fmt := fmt)
        ((unaryTotal fmt radix op)[Model.toNatBits x]'hindex).toNat =
      op x := by
  unfold unaryTotal at hindex ⊢
  rw [ByteArray.getElem_ofFn]
  rw [ofNatBits_toNatBits]
  rw [UInt8.toNat_ofNat', Nat.mod_eq_of_lt hz]
  exact ofNatBits_toNatBits (op x)

/-- Reading a total ternary-operation table returns the logical operation result. -/
theorem lookupTernaryTotal
    (fmt : FloatFormat) (radix : Nat) (hradix : 0 < radix)
    (op : Model fmt → Model fmt → Model fmt → Model fmt)
    (x y z : Model fmt)
    (hy : Model.toNatBits y < radix)
    (hz : Model.toNatBits z < radix)
    (hresult : Model.toNatBits (op x y z) < 256)
    (hindex :
      (Model.toNatBits x * radix + Model.toNatBits y) * radix +
          Model.toNatBits z <
        (ternaryTotal fmt radix op).size) :
    Model.ofNatBits (fmt := fmt)
        ((ternaryTotal fmt radix op)[
          (Model.toNatBits x * radix + Model.toNatBits y) * radix +
            Model.toNatBits z]'hindex).toNat =
      op x y z := by
  have hx : x.toNatBits < radix := by
    have hsize : (x.toNatBits * radix + y.toNatBits) * radix + z.toNatBits <
        radix * radix * radix := by
      simpa only [ternaryTotal, ByteArray.size_ofFn] using hindex
    have hpair : x.toNatBits * radix + y.toNatBits < radix * radix :=
      Nat.lt_of_mul_lt_mul_right (Nat.lt_of_le_of_lt (Nat.le_add_right _ _) hsize)
    exact (Nat.mul_lt_mul_right hradix).mp
      (Nat.lt_of_le_of_lt (Nat.le_add_right _ _) hpair)
  have hentry := Tabulation.getElem_ternary radix
    (fun a b c => UInt8.ofNat
      (op (Model.ofNatBits (fmt := fmt) a.val)
        (Model.ofNatBits b.val) (Model.ofNatBits c.val)).toNatBits)
    ⟨x.toNatBits, hx⟩ ⟨y.toNatBits, hy⟩ ⟨z.toNatBits, hz⟩ hindex
  unfold ternaryTotal
  rw [hentry]
  simp only [ofNatBits_toNatBits, UInt8.toNat_ofNat', Nat.mod_eq_of_lt hresult]

/--
Read a lazily memoized binary table through the ordinary `Model` carrier.

The table equation is an explicit argument so concrete format modules never need to unfold a
large generator while elaborating either the implementation or its refinement theorem.
-/
@[inline] def runLazyBinaryTotal
    (fmt : FloatFormat) (radix : Nat)
    (op : Model fmt → Model fmt → Model fmt)
    (table : Thunk ByteArray)
    (table_eq :
      table.get = binaryTotal fmt radix op)
    (x y : Model fmt)
    (hx : x.toNatBits < radix)
    (hy : y.toNatBits < radix) : Model fmt := by
  exact Model.ofNatBits (fmt := fmt)
    ((table.get)[x.toNatBits * radix + y.toNatBits]'(by
      rw [table_eq]
      exact binaryTotal_index_lt fmt radix op x y hx hy)).toNat

/-- A lazy binary-table read returns the operation used to generate the table. -/
theorem runLazyBinaryTotal_eq
    (fmt : FloatFormat) (radix : Nat) (hradix : 0 < radix)
    (op : Model fmt → Model fmt → Model fmt)
    (table : Thunk ByteArray)
    (table_eq :
      table.get = binaryTotal fmt radix op)
    (x y : Model fmt)
    (hx : x.toNatBits < radix)
    (hy : y.toNatBits < radix)
    (hresult : (op x y).toNatBits < 256) :
    runLazyBinaryTotal fmt radix op table table_eq x y hx hy = op x y := by
  simpa only [runLazyBinaryTotal, table_eq] using
    lookupTotal fmt radix hradix op x y hy hresult
      (binaryTotal_index_lt fmt radix op x y hx hy)

/-- Read a lazily memoized unary table through the ordinary `Model` carrier. -/
@[inline] def runLazyUnaryTotal
    (fmt : FloatFormat) (radix : Nat)
    (op : Model fmt → Model fmt)
    (table : Thunk ByteArray)
    (table_eq :
      table.get = unaryTotal fmt radix op)
    (x : Model fmt)
    (hx : x.toNatBits < radix) : Model fmt := by
  exact Model.ofNatBits (fmt := fmt)
    ((table.get)[x.toNatBits]'(by
      rw [table_eq]
      simpa only [unaryTotal, ByteArray.size_ofFn] using hx)).toNat

/-- A lazy unary-table read returns the operation used to generate the table. -/
theorem runLazyUnaryTotal_eq
    (fmt : FloatFormat) (radix : Nat)
    (op : Model fmt → Model fmt)
    (table : Thunk ByteArray)
    (table_eq :
      table.get = unaryTotal fmt radix op)
    (x : Model fmt)
    (hx : x.toNatBits < radix)
    (hresult : (op x).toNatBits < 256) :
    runLazyUnaryTotal fmt radix op table table_eq x hx = op x := by
  simpa only [runLazyUnaryTotal, table_eq] using
    lookupUnaryTotal fmt radix op x hresult (by
      simpa only [unaryTotal, ByteArray.size_ofFn] using hx)

/-- Read a lazily memoized ternary table through the ordinary `Model` carrier. -/
@[inline] def runLazyTernaryTotal
    (fmt : FloatFormat) (radix : Nat)
    (op : Model fmt → Model fmt → Model fmt → Model fmt)
    (table : Thunk ByteArray)
    (table_eq :
      table.get = ternaryTotal fmt radix op)
    (x y z : Model fmt)
    (hx : x.toNatBits < radix)
    (hy : y.toNatBits < radix)
    (hz : z.toNatBits < radix) : Model fmt := by
  exact Model.ofNatBits (fmt := fmt)
    ((table.get)[
      (x.toNatBits * radix + y.toNatBits) * radix + z.toNatBits]'(by
        rw [table_eq]
        exact ternaryTotal_index_lt fmt radix op x y z hx hy hz)).toNat

/-- A lazy ternary-table read returns the operation used to generate the table. -/
theorem runLazyTernaryTotal_eq
    (fmt : FloatFormat) (radix : Nat) (hradix : 0 < radix)
    (op : Model fmt → Model fmt → Model fmt → Model fmt)
    (table : Thunk ByteArray)
    (table_eq :
      table.get = ternaryTotal fmt radix op)
    (x y z : Model fmt)
    (hx : x.toNatBits < radix)
    (hy : y.toNatBits < radix)
    (hz : z.toNatBits < radix)
    (hresult : (op x y z).toNatBits < 256) :
    runLazyTernaryTotal fmt radix op table table_eq x y z hx hy hz = op x y z := by
  simpa only [runLazyTernaryTotal, table_eq] using
    lookupTernaryTotal fmt radix hradix op x y z hy hz hresult
      (ternaryTotal_index_lt fmt radix op x y z hx hy hz)

end TinyTable
end FloatLib.Floats.Formats.BinaryInterchange.Model
