/-
Copyright (c) 2026 FloatLib
Released under MIT license as described in the file LICENSE.
Authors: FloatLib Team
-/

module

public import FloatLib.Floats.ExecFloat.Backends.TinyTable.Generic.Runtime

/-!
# Semantic refinement of byte-table execution

These theorems prove that each direct byte lookup returns the encoding of the reference exact model
operation. Format packages can therefore compose fast execution with their own arithmetic proofs
without exposing table internals to users.
-/

@[expose] public section

namespace FloatLib.Floats.ExecFloat.Backend.TinyTable

universe u

variable {Model : Type u}

/-- A binary thunk read returns the code generated by its reference model operation. -/
theorem runBinaryCode_eq
    (encoding : Encoding Model)
    (op : Model → Model → Model) (table : Thunk ByteArray)
    (table_eq : table.get = binaryTotal encoding op)
    (left right : Code encoding) :
    runBinaryCode encoding op table table_eq left right =
      UInt8.ofNat
        (encoding.encode
          (op (encoding.decodeCode left) (encoding.decodeCode right))).val := by
  unfold runBinaryCode
  simpa only [table_eq] using
    lookupBinary encoding op left right
      (binaryIndex_lt encoding op left right)

/-- Binary table execution returns the direct encoding of the reference model operation. -/
theorem runBinary_eq_encodeCode
    (encoding : Encoding Model)
    (op : Model → Model → Model) (table : Thunk ByteArray)
    (table_eq : table.get = binaryTotal encoding op)
    (left right : Code encoding) :
    runBinary encoding op table table_eq left right =
      encoding.encodeCode
        (op (encoding.decodeCode left) (encoding.decodeCode right)) := by
  apply Subtype.ext
  exact runBinaryCode_eq encoding op table table_eq left right

/-- Decoding a binary table result yields the reference model operation. -/
@[simp] theorem decodeCode_runBinary
    (encoding : Encoding Model)
    (op : Model → Model → Model) (table : Thunk ByteArray)
    (table_eq : table.get = binaryTotal encoding op)
    (left right : Code encoding) :
    encoding.decodeCode
        (runBinary encoding op table table_eq left right) =
      op (encoding.decodeCode left) (encoding.decodeCode right) := by
  rw [runBinary_eq_encodeCode, encoding.decodeCode_encodeCode]

/-- A unary thunk read returns the code generated by its reference model operation. -/
theorem runUnaryCode_eq
    (encoding : Encoding Model) (op : Model → Model)
    (table : Thunk ByteArray) (table_eq : table.get = unaryTotal encoding op)
    (value : Code encoding) :
    runUnaryCode encoding op table table_eq value =
      UInt8.ofNat
        (encoding.encode (op (encoding.decodeCode value))).val := by
  unfold runUnaryCode
  simpa only [table_eq] using
    lookupUnary encoding op value (unaryIndex_lt encoding op value)

/-- Unary table execution returns the direct encoding of the reference model operation. -/
theorem runUnary_eq_encodeCode
    (encoding : Encoding Model) (op : Model → Model)
    (table : Thunk ByteArray) (table_eq : table.get = unaryTotal encoding op)
    (value : Code encoding) :
    runUnary encoding op table table_eq value =
      encoding.encodeCode (op (encoding.decodeCode value)) := by
  apply Subtype.ext
  exact runUnaryCode_eq encoding op table table_eq value

/-- Decoding a unary table result yields the reference model operation. -/
@[simp] theorem decodeCode_runUnary
    (encoding : Encoding Model) (op : Model → Model)
    (table : Thunk ByteArray) (table_eq : table.get = unaryTotal encoding op)
    (value : Code encoding) :
    encoding.decodeCode (runUnary encoding op table table_eq value) =
      op (encoding.decodeCode value) := by
  rw [runUnary_eq_encodeCode, encoding.decodeCode_encodeCode]

/-- A ternary thunk read returns the code generated by its reference model operation. -/
theorem runTernaryCode_eq
    (encoding : Encoding Model)
    (op : Model → Model → Model → Model)
    (table : Thunk ByteArray) (table_eq : table.get = ternaryTotal encoding op)
    (left right addend : Code encoding) :
    runTernaryCode encoding op table table_eq left right addend =
      UInt8.ofNat
        (encoding.encode
          (op (encoding.decodeCode left) (encoding.decodeCode right)
            (encoding.decodeCode addend))).val := by
  unfold runTernaryCode
  simpa only [table_eq] using
    lookupTernary encoding op left right addend
      (ternaryIndex_lt encoding op left right addend)

/-- Ternary table execution returns the direct encoding of the reference model operation. -/
theorem runTernary_eq_encodeCode
    (encoding : Encoding Model)
    (op : Model → Model → Model → Model)
    (table : Thunk ByteArray) (table_eq : table.get = ternaryTotal encoding op)
    (left right addend : Code encoding) :
    runTernary encoding op table table_eq left right addend =
      encoding.encodeCode
        (op (encoding.decodeCode left) (encoding.decodeCode right)
          (encoding.decodeCode addend)) := by
  apply Subtype.ext
  exact
    runTernaryCode_eq encoding op table table_eq left right addend

/-- Decoding a ternary table result yields the reference model operation. -/
@[simp] theorem decodeCode_runTernary
    (encoding : Encoding Model)
    (op : Model → Model → Model → Model)
    (table : Thunk ByteArray) (table_eq : table.get = ternaryTotal encoding op)
    (left right addend : Code encoding) :
    encoding.decodeCode
        (runTernary encoding op table table_eq left right addend) =
      op (encoding.decodeCode left) (encoding.decodeCode right)
        (encoding.decodeCode addend) := by
  rw [runTernary_eq_encodeCode, encoding.decodeCode_encodeCode]

end FloatLib.Floats.ExecFloat.Backend.TinyTable
