/-
Copyright (c) 2026 FloatLib
Released under MIT license as described in the file LICENSE.
Authors: FloatLib Team
-/

module

public import FloatLib.Floats.Formats.Flocq.Theory.Format.Formats
public import FloatLib.Floats.Formats.Flocq.Theory.Format.Generic

/-!
# Standard Format Theorems

Connections between the generic format predicate and the concrete FIX, FLX, and FLT families.
The fixed-point equivalence is the first instance of the generic pattern used by the floating-point
families.
-/

@[expose] public section

namespace FloatLib.Floats.Formats.Flocq

variable {β : Numerics.Radix}

/-- The generic format generated by `fixExp emin` is contained in `FIXFormat emin`. -/
theorem fixFormat_of_generic (emin : ℤ) (x : ℝ)
    (hx : genericFormat β (fixExp emin) x) : FIXFormat (β := β) emin x := by
  refine ⟨
    { mantissa := ⌊scaledMantissa β (fixExp emin) x⌋, exponent := emin }, ?_, rfl⟩
  simpa [genericFormat, cexp, fixExp] using hx

/-- Every fixed-point value belongs to the generic format generated by `fixExp emin`. -/
theorem generic_of_fixFormat (emin : ℤ) (x : ℝ) (hx : FIXFormat (β := β) emin x) :
    genericFormat β (fixExp emin) x := by
  obtain ⟨f, hxf, hfe⟩ := hx
  apply generic_format_of_scaled_mantissa_int
    (β := β) (fexp := fixExp emin) x f.mantissa
  calc
    scaledMantissa β (fixExp emin) x = x * bpow β (-emin) := by
      simp [scaledMantissa, cexp, fixExp]
    _ = ((f.mantissa : ℝ) * bpow β f.exponent) * bpow β (-emin) := by
      rw [hxf, toReal]
    _ = ((f.mantissa : ℝ) * bpow β emin) * bpow β (-emin) := by rw [hfe]
    _ = (f.mantissa : ℝ) * (bpow β emin * bpow β (-emin)) := by ring
    _ = (f.mantissa : ℝ) * bpow β (emin + -emin) := by
      rw [bpow.add_exp]
    _ = f.mantissa := by simp [bpow]

/-- `FIXFormat` and the corresponding generic format describe the same real values. -/
theorem generic_format_FIX_iff (emin : ℤ) (x : ℝ) :
    genericFormat β (fixExp emin) x ↔ FIXFormat (β := β) emin x :=
  ⟨fixFormat_of_generic emin x, generic_of_fixFormat emin x⟩

/-- A radix power with nonnegative exponent agrees with the corresponding natural-number power. -/
theorem bpow_eq_natPow (p : ℤ) (hp : 0 ≤ p) :
    bpow β p = (β.base ^ p.toNat : ℕ) := by
  obtain ⟨n, rfl⟩ := Int.eq_ofNat_of_zero_le hp
  simp [bpow, Numerics.Radix.toReal]

/-- The generic `flxExp` format satisfies the explicit FLX mantissa bound. -/
theorem flxFormat_of_generic (prec : ℤ) (hprec : 0 < prec) (x : ℝ)
    (hx : @genericFormat β (flxExp prec) (flxValidExp prec hprec) x) :
    FLXFormat (β := β) prec x := by
  let : ValidExp (flxExp prec) := flxValidExp prec hprec
  let m : ℤ := ⌊scaledMantissa β (flxExp prec) x⌋
  let e : ℤ := cexp β (flxExp prec) x
  have hsint : scaledMantissa β (flxExp prec) x = m := by
    obtain ⟨n, hn⟩ :=
      (generic_format_iff_scaled_mantissa_int
        (β := β) (fexp := flxExp prec) x).mp hx
    dsimp [m]
    rw [hn]
    simp
  refine ⟨hprec, { mantissa := m, exponent := e }, ?_, ?_⟩
  · unfold genericFormat at hx
    change x = (m : ℝ) * bpow β e
    exact hx
  · by_cases hx0 : x = 0
    · subst x
      have hm0 : m = 0 := by simp [m, scaledMantissa]
      rw [hm0]
      exact pow_pos (Nat.zero_lt_of_lt β.base_valid) _
    · have hbpos : 0 < bpow β e := bpow.pos β e
      have he : e = magnitude β x - prec := by simp [e, cexp, flxExp]
      have hsdiv : scaledMantissa β (flxExp prec) x =
          x / bpow β e :=
        scaledMantissa_eq_div (β := β) (fexp := flxExp prec) x
      have hslt : abs (scaledMantissa β (flxExp prec) x) < bpow β prec := by
        rw [hsdiv, abs_div, abs_of_pos hbpos, he]
        calc
          abs x / bpow β (magnitude β x - prec) <
              bpow β (magnitude β x) /
                bpow β (magnitude β x - prec) :=
            (div_lt_div_iff_of_pos_right (bpow.pos β _)).2
              (abs_lt_bpow_magnitude β x hx0)
          _ = bpow β prec := by
            rw [← bpow.sub_exp]
            congr 1
            linarith
      have hmcast : (m.natAbs : ℝ) < bpow β prec := by
        rw [hsint] at hslt
        have hmabs : (m.natAbs : ℝ) = abs (m : ℝ) := by
          cases m with
          | ofNat n => simp
          | negSucc n =>
              rw [Int.cast_negSucc, abs_of_neg]
              · norm_num
              · exact neg_neg_of_pos (by positivity : (0 : ℝ) < (n + 1 : ℕ))
        rwa [hmabs]
      have hpnonneg : 0 ≤ prec := hprec.le
      rw [bpow_eq_natPow (β := β) prec hpnonneg] at hmcast
      exact_mod_cast hmcast

/-- Every explicit bounded-mantissa FLX value belongs to the corresponding generic format. -/
theorem generic_of_flxFormat (prec : ℤ) (hprec : 0 < prec) (x : ℝ)
    (hx : FLXFormat (β := β) prec x) :
    @genericFormat β (flxExp prec) (flxValidExp prec hprec) x := by
  let : ValidExp (flxExp prec) := flxValidExp prec hprec
  obtain ⟨_, f, hxf, hmant⟩ := hx
  by_cases hm0 : f.mantissa = 0
  · have hx0 : x = 0 := by simp [hxf, toReal, hm0]
    rw [hx0]
    exact generic_format_zero
  · have hx0 : x ≠ 0 := by
      rw [hxf, toReal]
      exact mul_ne_zero (by exact_mod_cast hm0) (bpow.ne_zero β f.exponent)
    have hmabs : abs (f.mantissa : ℝ) = (f.mantissa.natAbs : ℝ) := by
      cases f.mantissa with
      | ofNat n => simp
      | negSucc n =>
          rw [Int.cast_negSucc, abs_of_neg]
          · norm_num
          · exact neg_neg_of_pos (by positivity : (0 : ℝ) < (n + 1 : ℕ))
    have hpnonneg : 0 ≤ prec := hprec.le
    have hmantR : abs (f.mantissa : ℝ) < bpow β prec := by
      rw [hmabs, bpow_eq_natPow (β := β) prec hpnonneg]
      exact_mod_cast hmant
    have habsx : abs x < bpow β (f.exponent + prec) := by
      rw [hxf, toReal, abs_mul, abs_of_pos (bpow.pos β f.exponent)]
      calc
        abs (f.mantissa : ℝ) * bpow β f.exponent <
            bpow β prec * bpow β f.exponent :=
          mul_lt_mul_of_pos_right hmantR (bpow.pos β f.exponent)
        _ = bpow β (f.exponent + prec) := by
          rw [← bpow.add_exp]
          congr 1
          linarith
    have hmag : magnitude β x ≤ f.exponent + prec :=
      magnitude_le_of_abs_lt_bpow β x (f.exponent + prec) hx0 habsx
    have hcexp : cexp β (flxExp prec) x ≤ f.exponent := by
      simp [cexp, flxExp]
      linarith
    exact generic_format_of_toReal_of_cexp_le f x hxf hcexp

/-- `FLXFormat` is exactly the generic format generated by `flxExp`. -/
theorem generic_format_FLX_iff (prec : ℤ) (hprec : 0 < prec) (x : ℝ) :
    @genericFormat β (flxExp prec) (flxValidExp prec hprec) x ↔
      FLXFormat (β := β) prec x :=
  ⟨flxFormat_of_generic prec hprec x, generic_of_flxFormat prec hprec x⟩

/-- The generic `fltExp` format satisfies the explicit FLT mantissa and exponent bounds. -/
theorem fltFormat_of_generic (emin prec : ℤ) (hprec : 0 < prec) (x : ℝ)
    (hx : @genericFormat β (fltExp emin prec) (fltValidExp emin prec hprec) x) :
    FLTFormat (β := β) emin prec x := by
  let : ValidExp (fltExp emin prec) := fltValidExp emin prec hprec
  let m : ℤ := ⌊scaledMantissa β (fltExp emin prec) x⌋
  let e : ℤ := cexp β (fltExp emin prec) x
  have hsint : scaledMantissa β (fltExp emin prec) x = m := by
    obtain ⟨n, hn⟩ :=
      (generic_format_iff_scaled_mantissa_int
        (β := β) (fexp := fltExp emin prec) x).mp hx
    dsimp [m]
    rw [hn]
    simp
  refine ⟨hprec, { mantissa := m, exponent := e }, ?_, ?_, ?_⟩
  · unfold genericFormat at hx
    change x = (m : ℝ) * bpow β e
    exact hx
  · by_cases hx0 : x = 0
    · subst x
      have hm0 : m = 0 := by simp [m, scaledMantissa]
      rw [hm0]
      exact pow_pos (Nat.zero_lt_of_lt β.base_valid) _
    · have hbpos : 0 < bpow β e := bpow.pos β e
      have he : e = max (magnitude β x - prec) emin := by
        simp [e, cexp, fltExp]
      have hsdiv : scaledMantissa β (fltExp emin prec) x =
          x / bpow β e :=
        scaledMantissa_eq_div (β := β) (fexp := fltExp emin prec) x
      have hdiff : magnitude β x - e ≤ prec := by
        rw [he]
        have := le_max_left (magnitude β x - prec) emin
        linarith
      have hslt : abs (scaledMantissa β (fltExp emin prec) x) <
          bpow β prec := by
        rw [hsdiv, abs_div, abs_of_pos hbpos]
        calc
          abs x / bpow β e <
              bpow β (magnitude β x) / bpow β e :=
            (div_lt_div_iff_of_pos_right hbpos).2
              (abs_lt_bpow_magnitude β x hx0)
          _ = bpow β (magnitude β x - e) :=
            (bpow.sub_exp β _ _).symm
          _ ≤ bpow β prec :=
            (bpow_le_bpow_iff β _ _).2 hdiff
      have hmcast : (m.natAbs : ℝ) < bpow β prec := by
        rw [hsint] at hslt
        have hmabs : (m.natAbs : ℝ) = abs (m : ℝ) := by
          cases m with
          | ofNat n => simp
          | negSucc n =>
              rw [Int.cast_negSucc, abs_of_neg]
              · norm_num
              · exact neg_neg_of_pos (by positivity : (0 : ℝ) < (n + 1 : ℕ))
        rwa [hmabs]
      rw [bpow_eq_natPow (β := β) prec hprec.le] at hmcast
      exact_mod_cast hmcast
  · simp [e, cexp, fltExp]

/-- Every explicit bounded-mantissa FLT value belongs to the corresponding generic format. -/
theorem generic_of_fltFormat (emin prec : ℤ) (hprec : 0 < prec) (x : ℝ)
    (hx : FLTFormat (β := β) emin prec x) :
    @genericFormat β (fltExp emin prec) (fltValidExp emin prec hprec) x := by
  let : ValidExp (fltExp emin prec) := fltValidExp emin prec hprec
  obtain ⟨_, f, hxf, hmant, hexp⟩ := hx
  by_cases hm0 : f.mantissa = 0
  · have hx0 : x = 0 := by simp [hxf, toReal, hm0]
    rw [hx0]
    exact generic_format_zero
  · have hx0 : x ≠ 0 := by
      rw [hxf, toReal]
      exact mul_ne_zero (by exact_mod_cast hm0) (bpow.ne_zero β f.exponent)
    have hmabs : abs (f.mantissa : ℝ) = (f.mantissa.natAbs : ℝ) := by
      cases f.mantissa with
      | ofNat n => simp
      | negSucc n =>
          rw [Int.cast_negSucc, abs_of_neg]
          · norm_num
          · exact neg_neg_of_pos (by positivity : (0 : ℝ) < (n + 1 : ℕ))
    have hmantR : abs (f.mantissa : ℝ) < bpow β prec := by
      rw [hmabs, bpow_eq_natPow (β := β) prec hprec.le]
      exact_mod_cast hmant
    have habsx : abs x < bpow β (f.exponent + prec) := by
      rw [hxf, toReal, abs_mul, abs_of_pos (bpow.pos β f.exponent)]
      calc
        abs (f.mantissa : ℝ) * bpow β f.exponent <
            bpow β prec * bpow β f.exponent :=
          mul_lt_mul_of_pos_right hmantR (bpow.pos β f.exponent)
        _ = bpow β (f.exponent + prec) := by
          rw [← bpow.add_exp]
          congr 1
          linarith
    have hmag : magnitude β x ≤ f.exponent + prec :=
      magnitude_le_of_abs_lt_bpow β x (f.exponent + prec) hx0 habsx
    have hcexp : cexp β (fltExp emin prec) x ≤ f.exponent := by
      simp [cexp, fltExp]
      constructor <;> linarith
    exact generic_format_of_toReal_of_cexp_le f x hxf hcexp

/-- `FLTFormat` is exactly the generic format generated by `fltExp`. -/
theorem generic_format_FLT_iff (emin prec : ℤ) (hprec : 0 < prec) (x : ℝ) :
    @genericFormat β (fltExp emin prec) (fltValidExp emin prec hprec) x ↔
      FLTFormat (β := β) emin prec x :=
  ⟨fltFormat_of_generic emin prec hprec x, generic_of_fltFormat emin prec hprec x⟩

end FloatLib.Floats.Formats.Flocq
